export const environment = {
  articleRootUrl: 'http://localhost:4200/',
};

export const FIREBASECONFIG_APIKEY="FIREBASECONFIG_APIKEY"
export const FIREBASECONFIG_AUTHDOMAIN="FIREBASECONFIG_AUTHDOMAIN"
export const FIREBASECONFIG_PROJECTID="FIREBASECONFIG_PROJECTID"
export const FIREBASECONFIG_STORAGEBUCKET="FIREBASECONFIG_STORAGEBUCKET"
export const FIREBASECONFIG_MESSAGINGSENDERID="FIREBASECONFIG_MESSAGINGSENDERID"
export const FIREBASECONFIG_APPID="FIREBASECONFIG_APPID"
export const FIREBASECONFIG_MEASUREMENTID="FIREBASECONFIG_MEASUREMENTID"
